
/* Drop Tables */

DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE ORDER_ITEM CASCADE CONSTRAINTS;
DROP TABLE RECEIVE CASCADE CONSTRAINTS;
DROP TABLE WISH_ITEM CASCADE CONSTRAINTS;
DROP TABLE ITEM CASCADE CONSTRAINTS;
DROP TABLE useraccount CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;


select * from USERACCOUNT

/* Create Tables */

CREATE TABLE BOARD
(
	BORAD_ID number NOT NULL,
	MEMBER_ID varchar2(15) NOT NULL,
	TITLE varchar2(100),
	CONTENT varchar2(4000),
	MEMBER_NAME varchar2(20),
	FILE_ID varchar2(100),
	BOARD_TYPE varchar2(12),
	READ_COUNT number,
	BOARD_NUMBER number,
	GRP_LEVEL number,
	GRP_STEP number,
	STATUS char(1),
	CREATE_DATE date,
	UPDATE_DATE date,
	PRIMARY KEY (BORAD_ID)
);


CREATE TABLE ITEM
(
	ITEM_ID number NOT NULL,
	ITEM_NAME varchar2(30),
	ITEM_PRICE number,
	FILE_ID varchar2(100),
	ITEM_INFORMATION varchar2(100),
	ITEM_TYPE varchar2(20),
	ITEM_QUALITY varchar2(10),
	STATUS char(1),
	PRIMARY KEY (ITEM_ID)
);




create table useraccount (
   userid varchar2(10) primary key,
   password varchar2(15),
   username varchar2(20),
   MEMBER_TYPE number,
   POINT number,
   phoneno varchar2(20),
   postcode varchar2(7),
   address varchar2(30),
   email varchar2(50),
   STATUS char(1),
   birthday date
);

CREATE TABLE ORDERS
(
	ORDER_ID number NOT NULL,
	USER_ID varchar2(10) NOT NULL,
	ORDER_DATE date,
	STATUS char(1),
	PRIMARY KEY (ORDER_ID)
);


CREATE TABLE ORDER_ITEM
(
	ORDER_ID number NOT NULL,
	ORDER_SEQ number NOT NULL,
	ITEM_ID number NOT NULL,
	ORDER_PRICE number,
	ORDER_QUANTITY number,
	STATUS char(1),
	PRIMARY KEY (ORDER_ID, ORDER_SEQ)
);


CREATE TABLE RECEIVE
(
	ITEM_ID number NOT NULL,
	PUT_ON_COUNT number,
	PUT_ON_DATE date,
	STATUS char(1)
);


CREATE TABLE REVIEW
(
	REVIEW_ID number NOT NULL,
	ORDER_ID number NOT NULL,
	MEMBER_ID varchar2(15) NOT NULL,
	MEMBER_NAME varchar2(20),
	TITLE varchar2(100),
	CONTENT varchar2(4000),
	STAR number NOT NULL,
	STATUS char(1),
	CREATE_DATE date,
	UPDATE_DATE date,
	ORDER_SEQ number NOT NULL,
	PRIMARY KEY (REVIEW_ID)
);


CREATE TABLE WISH_ITEM
(
	WISH_ITEM_ID number NOT NULL,
	ITEM_ID number NOT NULL,
	MEMBER_ID varchar2(15) NOT NULL,
	STATUS char(1),
	PRIMARY KEY (WISH_ITEM_ID, ITEM_ID, MEMBER_ID)
);



/* Create Foreign Keys */

ALTER TABLE ORDER_ITEM
	ADD FOREIGN KEY (ITEM_ID)
	REFERENCES ITEM (ITEM_ID)
;


ALTER TABLE RECEIVE
	ADD FOREIGN KEY (ITEM_ID)
	REFERENCES ITEM (ITEM_ID)
;


ALTER TABLE WISH_ITEM
	ADD FOREIGN KEY (ITEM_ID)
	REFERENCES ITEM (ITEM_ID)
;


ALTER TABLE BOARD
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBERS (MEMBER_ID)
;


ALTER TABLE REVIEW
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBERS (MEMBER_ID)
;


ALTER TABLE WISH_ITEM
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBERS (MEMBER_ID)
;


ALTER TABLE ORDER_ITEM
	ADD FOREIGN KEY (ORDER_ID)
	REFERENCES ORDERS (ORDER_ID)
;


ALTER TABLE REVIEW
	ADD FOREIGN KEY (ORDER_ID, ORDER_SEQ)
	REFERENCES ORDER_ITEM (ORDER_ID, ORDER_SEQ)
;

select * from useraccount

